rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx
gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.1_ProtectedAttributes.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-head
